source:
  folder: ./dbf            # путь к папке с DBF файлами
  pattern: ????xxxx.dbf     # шаблон поиска файлов, xxxx заменяется на год

db:
  type: sqlite             # или 'postgres'
  sqlite_path: ./db.sqlite  # путь к sqlite базе
  # параметры PostgreSQL (если используется)
  # host: 127.0.0.1
  # port: 5432
  # dbname: reports
  # user: postgres
  # password: secret

state_file: ./state.json   # файл состояния обработанных файлов
log_file: ./dbf_sync.log   # файл логов
batch_size: 1000           # размер пакета вставки
