name: Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pylint
        poetry install
    - name: Lint with pylint
      run: poetry run pylint **/*.py --rcfile=pylint.yml

  test:
    runs-on: ubuntu-latest
    needs: lint  # Запускать тесты после линтинга
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest
        poetry install
    - name: Test with pytest
      run: poetry run pytest

  build:
    runs-on: ubuntu-latest
    needs: test  # Сборка после тестов
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Build package
      run: poetry build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: dist/*